### ISSUE TITLE
Create a hash of the post MBR gap

### ISSUE THREAD

**Issue by grazzolini** [grazzolini/mkinitcpio-chkcryptoboot#4]
In MBR systems, only the first 446 bytes of the boot loader code are hashed. This code is very small and basically is a pointer for calling GRUB's second stage, which normally is located on the post MBR gap. Since we can't (yet) know beforehand what the size of the second stage is, the only viable solution for now is to hash the entire post MBR gap. This gap is at least 31 Kib large. But normally is 1 Mib or more.

**Comment by mathewmarcus** [comment]
On a a related note, would you be interested in support for BIOS systems with a GPT, which would require a BIOS boot partition as described in the [Arch Wiki](https://wiki.archlinux.org/index.php/GRUB#GUID_Partition_Table_.28GPT.29_specific_instructions)? This would likely involve an additional section(s) in the config file and then hashing of the BIOS boot partition. And would you be open to architecture discussions and/or a pull request for this and the aforementioned support for hashing of the post-MBR gap?

**Comment by grazzolini** [comment]
@mathewmarcus 

I don't see why not. But one thing to keep in mind is that the bios boot partition is not filled by the bootloader's code. As with the post mbr gap. This code could support both, but in the end it could trigger false positives. Unless the size of the second stage on the post mbr gap/boot partition is calculated and only it is read from there.

**Comment by mathewmarcus** [comment]
> But one thing to keep in mind is that the bios boot partition is not filled by the bootloader's code.

@grazzolini could you explain this further? From what I can find, if using a GPT, [the BIOS boot partition would contain the second stage of the bootloader](https://en.wikipedia.org/wiki/BIOS_boot_partition#Overview) just as the post-MBR gap would if using MBR. Or am I mistaken?

**Comment by grazzolini** [comment]
@mathewmarcus 
Yes, when using GPT with BIOS, the bios boot partition contains the second stage as does the post MBR gap. From the last time I have checked GRUB's source code, it doesn't use more than 62 sectors for the second stage (around 31KiB). But it might be smaller than that, and we would need to know this size or live with the fact that we are hashing the entire post MBR gap, which is usually 2MiB, or the bios boot partition and live with the possible, albeit slow, chance of false positives.

The most difficult case is the post MBR gap, because it's not a partition and it's not always the same size. We need to carefully calculate it's size and take a hash of it, using dd or something else. The bios boot partition is actually much simpler, we could just place two (or even one) setting in the config and it would be hashed.

**Comment by mathewmarcus** [comment]
So think I've just about got a working POC for this. I'd like to run some more tests but I should have a pull request submitted by the end of the weekend. Just so we're on the same page, I'd like to discuss some options regarding additional sections in the `chkryptoboot.conf`.

The first section I've added is as follows

```
#Path to grub core.img (only in case of mbr. e.g. /boot/grub/i386-pc/core.img)                                                                                                
CORE=
```

This section is pretty simple, it just specifies the location of the `core.img` file so we can get the size of the second stage and also get a hash of the file.

As far as the second section, I have two ideas. I figure we need some way to specify whether we want to read from the post-MBR gap or a BIOS boot partition, and I've thought of two options

1. Specify the partition table type, either `mbr` or `gpt`
2. Specify the PARTUUID of the BIOS boot partition

I personally like the first option because I think it keeps the `chkcryptoboot.conf` file cleaner and more intuitive. Since we already have the `BOOTDISK`, we could actually just loop through the different partitions of that disk, checking for a parttype UUID which matches that of a BIOS boot partition, specifically 21686148-6449-6E6F-744E-656564454649. The commands `blkid -p ${BOOTDISK}/${PARTITION}` or `lsblk -o parttype ${BOOTDISK}` would help accomplish this.

The second option would remove the need to do the aforementioned looping, since we would specify the partition in `chkcryptoboot.conf`, however I think it would make that file somewhat less clean/intuitive because the use of GPT would be implicit.

Anyway let me know what thoughts you have about all of this or if any of it seems confusing/incorrect. I've written two versions to test each of these options, so once we decide on one I can submit a pull request.

**Comment by grazzolini** [comment]
As far as I know, grub-install creates a custom second stage for each installation, depending on the hardware it detected and the modules it needs there. I don't think we can use the default core.img.

What I do know is that grub is hardcoded to not allow a second stage bigger than 62 sectors, or around 31KiB. We can start with that, it would trigger less false positives than hashing the entire partition or post MBR gap.

As for using partition types, I don't think that's a good idea. We should have options there that explicitly specify the bios boot partition, when using BIOS/GPT. When using BIOS/MBR and where the second stage is on the post MBR gap, then just specifying it as mbr would do. On all other cases, we need the partition there.

**Comment by mathewmarcus** [comment]
Just wanted to follow up on this, was there anything else you want added to/changed in the pull request?

**Comment by grazzolini** [comment]
Hi @mathewmarcus,

I did not had time to review the PR yet. I'll probably look into it this week and I'll let you know.
